name: Claude Code

on:
  issues:
    types: [labeled]

jobs:
  claude:
    if: |
      contains(github.event.label.name, 'claude') &&
      github.event.issue.user.login == 'calumrussell'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
          allowed_tools: "Bash(cargo:*)"
          custom_instructions: |
            Check details about the project in .claude/ folder.
